"""empty message

Revision ID: 21fad95a27bf
Revises: 
Create Date: 2024-09-29 21:04:34.287344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import ormar


# revision identifiers, used by Alembic.
revision: str = '21fad95a27bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'PAID', 'CANCELLED', 'SENT', name='orderstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=14, scale=2), nullable=False),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_table('orderitems',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=False),
    sa.Column('order', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('product', ormar.fields.sqlalchemy_uuid.CHAR(32), nullable=True),
    sa.Column('quantity_in_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order'], ['orders.id'], name='fk_orderitems_orders_id_order'),
    sa.ForeignKeyConstraint(['product'], ['products.id'], name='fk_orderitems_products_id_product'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderitems_id'), 'orderitems', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orderitems_id'), table_name='orderitems')
    op.drop_table('orderitems')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
